# Generated by Django 4.2.7 on 2023-11-27 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('referral_code', models.CharField(max_length=12, unique=True)),
                ('referred_by', models.CharField(default=None, max_length=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
