# Generated by Django 4.2.7 on 2023-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_email_collector', '0002_alter_emails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
