# Generated by Django 4.2.7 on 2023-12-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_email_collector', '0003_alter_emails_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name_plural': 'Email'},
        ),
    ]
