# Generated by Django 4.2.7 on 2023-12-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_email_collector', '0004_alter_emails_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emails',
            unique_together={('email',)},
        ),
    ]
