# Generated by Django 4.2.7 on 2023-12-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_email_collector', '0005_alter_emails_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterUniqueTogether(
            name='emails',
            unique_together=set(),
        ),
    ]
