version: '3.8'
volumes:
  static:
  
services:
  eduprene_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eduprene_web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn eduprene.wsgi:application --bind 0.0.0.0:8001"
    ports:
      - 8001:8001
    volumes:
      - ./static:/home/app/static
      - ./.env:/home/app/.env
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:7-alpine
    ports:
      - 6380:6379

  celery_worker:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: eduprene_celery_worker
    command: bash -c "celery -A eduprene worker -l info"
    volumes:
      - .:/home/app
      - ./.env:/home/app/.env
    depends_on:
      - redis

