# Generated by Django 4.2.7 on 2023-11-11 21:21
# Generated by Django 4.2.7 on 2023-11-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerlogs',
            options={'verbose_name_plural': 'Register Logs'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name_plural': 'Users Accounts'},
        ),
        migrations.AlterModelOptions(
            name='usersubscriptions',
            options={'verbose_name_plural': 'Users Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='registerlogs',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
    ]
