# Generated by Django 4.2.7 on 2023-11-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_registerlogs_options_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlogs',
            name='email',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerlogs',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
