# Generated by Django 4.2.7 on 2023-12-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_registerlogs_email_registerlogs_otp_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name_plural': "User's Accounts"},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='registerlogs',
            name='otp_trials',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registerlogs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
