# Generated by Django 4.2.7 on 2023-12-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_user_id_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
