# Generated by Django 4.2.7 on 2023-12-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0006_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
