# Generated by Django 4.2.7 on 2023-11-11 21:21
# Generated by Django 4.2.7 on 2023-11-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'verbose_name_plural': 'Users Bank Accounts'},
        ),
    ]
