# Generated by Django 4.2.7 on 2023-12-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_banks_options_alter_userbankaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'verbose_name_plural': "User's Bank Accounts"},
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
